// ============================================================
// hybrid-RUSTED — DifferentialRunner
// Spawns source (Python/C++) and Rust binaries in parallel with
// identical inputs generated by InputInjector.
//
// Harness contract (both sides):
//   ARGS:   <nodeId> <inputFile.json>
//   STDOUT: { "result": <value> }   (single JSON line)
//   STDERR: errors (ignored for diff, logged on failure)
//   EXIT:   0 = ok, 1 = error
//
// Harnesses are auto-generated by HarnessGenerator during `init`.
// Copyright 2026 Fabrizio Baroni — Apache 2.0
// ============================================================

import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { RustedConfig, WorkspaceInfo, OutputPair } from '../types';
import { InputInjector } from './InputInjector';
import type { TreeNode, InputField } from '../core/HarnessGenerator';

export class DifferentialRunner {
    private injector: InputInjector;

    constructor(private config: RustedConfig) {
        this.injector = new InputInjector(config);
    }

    /**
     * Runs N differential tests for a single node.
     * Reads inputSchema from the node's TREE entry if available.
     *
     * Source harness:  python3 run_node.py <nodeId> <inputFile.json>
     * Rust harness:    <rustWorkspace>/run_node/target/debug/run_node <nodeId> <inputFile.json>
     */
    async run(
        nodeId: string,
        source: WorkspaceInfo,
        rust: WorkspaceInfo
    ): Promise<OutputPair[]> {
        const schema = this.loadNodeSchema(nodeId, rust.treeJsonPath);
        const inputs = this.injector.inject(nodeId, schema);
        const pairs: OutputPair[] = [];

        for (let i = 0; i < inputs.inputFiles.length; i++) {
            const inputFile = inputs.inputFiles[i];

            const sourceOutput = this.runPythonHarness(source.rootDir, nodeId, inputFile);
            const rustOutput = this.runRustHarness(rust.rootDir, nodeId, inputFile);

            pairs.push({ runIndex: i, sourceOutput, rustOutput });
        }

        this.injector.cleanup(inputs);
        return pairs;
    }

    // ── Runners ───────────────────────────────────────────────────────────────

    private runPythonHarness(rootDir: string, nodeId: string, inputFile: string): string {
        const harness = path.join(rootDir, 'run_node.py');
        if (!fs.existsSync(harness)) {
            throw new Error(
                `Python harness not found: ${harness}\n` +
                `Run: hybrid-rusted init --source ${rootDir} --rust <dir>`
            );
        }
        return this.exec('python3', [harness, nodeId, inputFile], rootDir);
    }

    private runRustHarness(rootDir: string, nodeId: string, inputFile: string): string {
        const binary = path.join(rootDir, 'run_node', 'target', 'debug', 'run_node');
        if (!fs.existsSync(binary)) {
            throw new Error(
                `Rust harness not found: ${binary}\n` +
                `Run: cd ${path.join(rootDir, 'run_node')} && cargo build`
            );
        }
        return this.exec(binary, [nodeId, inputFile], rootDir);
    }

    private exec(cmd: string, args: string[], cwd: string): string {
        try {
            return execFileSync(cmd, args, {
                cwd,
                timeout: this.config.timeout_ms,
                encoding: 'utf-8',
            }).trim();
        } catch (err: unknown) {
            const msg = err instanceof Error ? err.message : String(err);
            return JSON.stringify({ __error__: msg });
        }
    }

    // ── Schema loader ─────────────────────────────────────────────────────────

    /**
     * Reads the node's inputSchema from hybrid-tree.json.
     * Returns undefined if the TREE has no schema (InputInjector will use fallback).
     */
    private loadNodeSchema(
        nodeId: string,
        treeJsonPath: string
    ): Record<string, InputField> | undefined {
        if (!fs.existsSync(treeJsonPath)) return undefined;

        const tree = JSON.parse(fs.readFileSync(treeJsonPath, 'utf-8'));
        const nodes = this.flattenTree(tree.nodes ?? tree.children ?? []);
        const node = nodes.find((n: TreeNode) => n.id === nodeId);
        return node?.inputSchema;
    }

    private flattenTree(nodes: TreeNode[]): TreeNode[] {
        const result: TreeNode[] = [];
        for (const n of nodes) {
            result.push(n);
            if (n.children?.length) result.push(...this.flattenTree(n.children));
        }
        return result;
    }
}
