// ============================================================
// hybrid-RUSTED — HarnessGenerator
// Generates run_node.py (source harness) and the Rust binary
// entrypoint run_node/src/main.rs from hybrid-tree.json data.
//
// Contract for both harnesses:
//   Args:   <nodeId> <inputFile.json>
//   Stdout: JSON result (single line)
//   Stderr: errors only
//   Exit:   0 on success, 1 on error
//
// Copyright 2026 Fabrizio Baroni — Apache 2.0
// ============================================================

import * as fs from 'fs';
import * as path from 'path';
import { RustedConfig, WorkspaceInfo } from '../types';

export interface TreeNode {
    id: string;
    label: string;
    intent: string;
    module: string;   // Python module path, e.g. "optuna.samplers.tpe"
    fnName: string;   // function/method name to call
    outputType: 'float' | 'integer' | 'string' | 'object' | 'float[]' | 'integer[]';
    epsilon?: 'float' | 'integer' | 'default';
    inputSchema: Record<string, InputField>;
    children: TreeNode[];
}

export interface InputField {
    type: 'float' | 'int' | 'string' | 'float[]' | 'int[]' | 'bool';
    range?: [number, number];
    length?: number;
    values?: unknown[]; // enum-like fixed choices
}

export class HarnessGenerator {
    constructor(private config: RustedConfig) { }

    /**
     * Reads hybrid-tree.json from the rust workspace (already copied by init)
     * and generates:
     *   <sourceWorkspace>/run_node.py    — Python harness
     *   <rustWorkspace>/run_node/src/main.rs  — Rust harness (cargo binary)
     *   <rustWorkspace>/run_node/Cargo.toml
     */
    generate(source: WorkspaceInfo, rust: WorkspaceInfo): void {
        if (!fs.existsSync(rust.treeJsonPath)) {
            console.warn(`   ⚠️  No hybrid-tree.json found — skipping harness generation.`);
            return;
        }

        const tree = JSON.parse(fs.readFileSync(rust.treeJsonPath, 'utf-8'));
        const nodes: TreeNode[] = this.flattenNodes(tree.nodes ?? tree.children ?? []);

        // Python harness
        const pyHarness = this.buildPythonHarness(nodes);
        const pyPath = path.join(source.rootDir, 'run_node.py');
        fs.writeFileSync(pyPath, pyHarness, 'utf-8');
        console.log(`   → Python harness: ${pyPath}`);

        // Rust harness binary
        const rustHarnessDir = path.join(rust.rootDir, 'run_node');
        fs.mkdirSync(path.join(rustHarnessDir, 'src'), { recursive: true });

        fs.writeFileSync(
            path.join(rustHarnessDir, 'Cargo.toml'),
            this.buildCargoToml(),
            'utf-8'
        );
        fs.writeFileSync(
            path.join(rustHarnessDir, 'src', 'main.rs'),
            this.buildRustHarness(nodes),
            'utf-8'
        );
        console.log(`   → Rust harness:   ${rustHarnessDir}/src/main.rs`);
    }

    // ── Python harness ─────────────────────────────────────────────────────────

    private buildPythonHarness(nodes: TreeNode[]): string {
        const dispatchCases = nodes
            .map(n => this.buildPythonCase(n))
            .join('\n');

        return `#!/usr/bin/env python3
"""
run_node.py — AUTO-GENERATED by hybrid-RUSTED
Test harness: imports source modules and calls a single node by ID.

Usage: python3 run_node.py <nodeId> <inputFile.json>
Output: JSON result on stdout
"""
import sys
import json

def dispatch(node_id: str, data: dict) -> object:
    """Route nodeId to the correct function call."""
${dispatchCases}
    raise ValueError(f"Unknown node: {node_id}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(json.dumps({"__error__": "Usage: run_node.py <nodeId> <inputFile.json>"}))
        sys.exit(1)

    node_id   = sys.argv[1]
    input_path = sys.argv[2]

    try:
        with open(input_path) as f:
            data = json.load(f)
        result = dispatch(node_id, data)
        print(json.dumps({"result": result}))
        sys.exit(0)
    except Exception as e:
        print(json.dumps({"__error__": str(e)}))
        sys.exit(1)
`;
    }

    private buildPythonCase(node: TreeNode): string {
        const params = Object.keys(node.inputSchema)
            .map(k => `data.get("${k}")`)
            .join(', ');
        const moduleImport = node.module
            ? `from ${node.module} import ${node.fnName}`
            : `# TODO: import ${node.fnName}`;

        return `    if node_id == "${node.id}":
        ${moduleImport}
        return ${node.fnName}(${params})`;
    }

    // ── Rust harness ───────────────────────────────────────────────────────────

    private buildCargoToml(): string {
        return `[package]
name = "run_node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "run_node"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
`;
    }

    private buildRustHarness(nodes: TreeNode[]): string {
        const structs = nodes
            .map(n => this.buildRustInputStruct(n))
            .join('\n\n');

        const matchArms = nodes
            .map(n =>
                `        "${n.id}" => {\n` +
                `            let input: ${this.toPascalCase(n.id)}Input = serde_json::from_value(data).expect("Invalid node input");\n` +
                `            // TODO: call ${n.fnName}(input)\n` +
                `            todo!("Call actual implementation for ${n.id} with {:?}", input)\n` +
                `        }`
            )
            .join(',\n');

        return `// AUTO-GENERATED by hybrid-RUSTED — Rust test harness
// Usage: ./run_node <nodeId> <inputFile.json>
// Output: JSON result on stdout

use std::env;
use std::fs;
use serde::{Deserialize, Serialize};

${structs}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() != 3 {
        eprintln!("Usage: run_node <nodeId> <inputFile.json>");
        std::process::exit(1);
    }

    let node_id   = &args[1];
    let input_raw = fs::read_to_string(&args[2]).expect("Cannot read input file");
    let data: serde_json::Value = serde_json::from_str(&input_raw).expect("Invalid JSON");

    let result: serde_json::Value = match node_id.as_str() {
${matchArms}
        other => {
            eprintln!("Unknown node: {}", other);
            std::process::exit(1);
        }
    };

    println!("{}", serde_json::json!({ "result": result }));
}

fn to_json<T: Serialize>(val: T) -> serde_json::Value {
    serde_json::to_value(val).unwrap()
}
`;
    }

    private buildRustInputStruct(node: TreeNode): string {
        const fields = Object.entries(node.inputSchema)
            .map(([name, field]) => {
                const rustType = this.mapToRustType(field.type);
                return `    pub ${name}: ${rustType},`;
            })
            .join('\n');

        return `#[derive(Debug, Serialize, Deserialize)]\n` +
            `pub struct ${this.toPascalCase(node.id)}Input {\n` +
            `${fields}\n` +
            `}`;
    }

    private mapToRustType(type: string): string {
        switch (type) {
            case 'float': return 'f64';
            case 'int': return 'i64';
            case 'bool': return 'bool';
            case 'string': return 'String';
            case 'float[]': return 'Vec<f64>';
            case 'int[]': return 'Vec<i64>';
            default: return 'serde_json::Value';
        }
    }

    private toPascalCase(str: string): string {
        return str
            .replace(/[^a-zA-Z0-9]+/g, ' ')
            .split(' ')
            .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
            .join('');
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private flattenNodes(nodes: TreeNode[]): TreeNode[] {
        const result: TreeNode[] = [];
        for (const node of nodes) {
            if (node.id && node.fnName) result.push(node);
            if (node.children?.length) {
                result.push(...this.flattenNodes(node.children));
            }
        }
        return result;
    }
}
