// ============================================================
// hybrid-RUSTED — ReverseTreeGenerator
// Reads orphan RCP nodes from source workspace and prepares
// structured context for AI to generate the Reverse-TREE
// (hybrid-tree.json)
// Copyright 2026 Fabrizio Baroni — Apache 2.0
// ============================================================

import * as fs from 'fs';
import * as path from 'path';
import { RustedConfig, WorkspaceInfo } from '../types';

interface RcpNode {
    id: string;
    file: string;
    language: string;
    exports: string[];
    imports: string[];
    lines: number;
    summary?: string;
}

export class ReverseTreeGenerator {
    private brainDir: string;

    constructor(private config: RustedConfig) {
        // Output goes to .brain/ (gitignored) in the source workspace
        this.brainDir = path.join(this.config.sourceWorkspace, '.brain');
    }

    /**
     * Reads hybrid-rcp.json, groups nodes by file/module, and writes a
     * structured Markdown prompt to .brain/reverse-tree-prompt.md.
     *
     * The AI (Antigravity) reads this prompt and produces hybrid-tree.json.
     * This module does NOT call the AI directly — it prepares the context.
     */
    generate(source: WorkspaceInfo): void {
        const rcp = JSON.parse(fs.readFileSync(source.rcpJsonPath, 'utf-8'));
        const nodes: RcpNode[] = rcp.nodes ?? [];

        fs.mkdirSync(this.brainDir, { recursive: true });

        const grouped = this.groupByLanguage(nodes);
        const prompt = this.buildPrompt(grouped, source.rootDir);

        const outPath = path.join(this.brainDir, 'reverse-tree-prompt.md');
        fs.writeFileSync(outPath, prompt, 'utf-8');
    }

    // ── Private ────────────────────────────────────────────────────────────────

    private groupByLanguage(nodes: RcpNode[]): Record<string, RcpNode[]> {
        return nodes.reduce<Record<string, RcpNode[]>>((acc, node) => {
            const lang = node.language ?? 'unknown';
            if (!acc[lang]) acc[lang] = [];
            acc[lang].push(node);
            return acc;
        }, {});
    }

    private buildPrompt(
        grouped: Record<string, RcpNode[]>,
        rootDir: string
    ): string {
        const lines: string[] = [
            `# Reverse-TREE Generation Prompt`,
            `> Auto-generated by hybrid-RUSTED — ${new Date().toISOString()}`,
            ``,
            `## Mission`,
            `Read the nodes below (all are ORPHAN — no TREE exists yet).`,
            `For each node, deduce the **logical intent** from the code structure.`,
            `Produce a \`hybrid-tree.json\` that describes WHAT the program does,`,
            `with enough detail to drive a 1:1 Rust re-implementation.`,
            ``,
            `**Rules:**`,
            `- Be as specific as possible: include algorithm names, data types, return values.`,
            `- Do NOT invent behavior — only document what the code structure evidence supports.`,
            `- Group nodes into logical modules (mirror the source structure).`,
            ``,
            `## Source Project`,
            `\`\`\``,
            `Root: ${rootDir}`,
            `\`\`\``,
            ``,
        ];

        for (const [lang, nodes] of Object.entries(grouped)) {
            lines.push(`## Language: ${lang} (${nodes.length} nodes)`);
            lines.push('');
            for (const node of nodes) {
                lines.push(`### Node: \`${node.id}\``);
                lines.push(`- **File:** \`${node.file}\``);
                lines.push(`- **Lines:** ${node.lines}`);
                lines.push(`- **Exports:** ${node.exports.join(', ') || '—'}`);
                lines.push(`- **Imports:** ${node.imports.join(', ') || '—'}`);
                if (node.summary) {
                    lines.push(`- **RCP Summary:** ${node.summary}`);
                }
                lines.push('');
            }
        }

        lines.push('---');
        lines.push('*Write hybrid-tree.json to the source workspace root.*');

        return lines.join('\n');
    }
}
