// ============================================================
// hybrid-RUSTED — SkeletonGenerator
// Reads Reverse-TREE (hybrid-tree.json) + GENESIS and generates
// empty Rust file/struct/fn skeletons in the rust workspace
// Copyright 2026 Fabrizio Baroni — Apache 2.0
// ============================================================

import * as fs from 'fs';
import * as path from 'path';
import { RustedConfig, WorkspaceInfo } from '../types';

interface TreeNode {
    id: string;
    label: string;
    intent: string;
    children: TreeNode[];
    rcpRef?: string;  // linked RCP node id
}

export class SkeletonGenerator {
    constructor(private config: RustedConfig) { }

    /**
     * Reads hybrid-tree.json from the rust workspace (copied from source)
     * and generates one Rust file per top-level module with typed stubs.
     *
     * Files are written as .rs files inside <rustWorkspace>/src/generated/
     * They are intentionally incomplete — AI fills in the logic.
     */
    generate(rust: WorkspaceInfo): void {
        if (!fs.existsSync(rust.treeJsonPath)) {
            console.warn(`   ⚠️  No hybrid-tree.json in Rust workspace — run init first.`);
            return;
        }

        const tree = JSON.parse(fs.readFileSync(rust.treeJsonPath, 'utf-8'));
        const roots: TreeNode[] = tree.nodes ?? tree.children ?? [];

        const outDir = path.join(rust.rootDir, 'src', 'generated');
        fs.mkdirSync(outDir, { recursive: true });

        const modNames: string[] = [];

        for (const root of roots) {
            const modName = this.toSnakeCase(root.label);
            const content = this.buildRustModule(root, modName);
            const filePath = path.join(outDir, `${modName}.rs`);
            fs.writeFileSync(filePath, content, 'utf-8');
            modNames.push(modName);
        }

        // Write mod.rs to expose all generated modules
        const modRs = modNames.map(m => `pub mod ${m};`).join('\n') + '\n';
        fs.writeFileSync(path.join(outDir, 'mod.rs'), modRs, 'utf-8');

        console.log(`   → Generated ${modNames.length} Rust modules in src/generated/`);
    }

    // ── Private ────────────────────────────────────────────────────────────────

    private buildRustModule(node: TreeNode, modName: string): string {
        const lines: string[] = [
            `// AUTO-GENERATED by hybrid-RUSTED — DO NOT EDIT`,
            `// Module: ${modName}`,
            `// Intent: ${node.intent ?? 'TODO: fill intent from Reverse-TREE'}`,
            `// RCP ref: ${node.rcpRef ?? 'N/A'}`,
            `//`,
            `// ⚠️  This is a skeleton. Implement the TODO! bodies.`,
            ``,
        ];

        // Recurse into children to generate nested fn stubs
        this.collectFunctions(node, lines, 0);

        return lines.join('\n');
    }

    private collectFunctions(node: TreeNode, lines: string[], depth: number): void {
        const fnName = this.toSnakeCase(node.label);
        const indent = '    '.repeat(depth);

        lines.push(`${indent}/// ${node.intent ?? node.label}`);
        lines.push(`${indent}pub fn ${fnName}(/* TODO: add params */) /* -> TODO: return type */ {`);
        lines.push(`${indent}    todo!("Implement: ${node.label}")`);
        lines.push(`${indent}}`);
        lines.push('');

        for (const child of node.children ?? []) {
            this.collectFunctions(child, lines, depth);
        }
    }

    private toSnakeCase(label: string): string {
        return label
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '_')
            .replace(/^_+|_+$/g, '');
    }
}
